# Site settings
title: Notes for ELEG5491: Introduction to Deep Learning
# email: karpathy@cs.stanford.edu
description: "Course materials and notes for CUHK ELEG5491: Introduction to Deep Learning."
baseurl: ""
url: "http://eleg5491.github.io"
twitter_username: dl_cuhk
github_username:  eleg5491

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

